parameters:
- name: stage
  default: stage
- name: displayName
  default: Deploy
- name: dependsOn
  default: ''
- name: pauseForCodeReview
  default: false
- name: failReleaseIfDriftDetected
  default: false
- name: staticCodeAnalysis
  default: false
- name: staticCodeAnalysisOnly
  default: false
- name: generateReport                              #This is the primary flag to turn off reports. TODO: Sanitize number of variables used here.
  default: true
- name: targetCredentials
  default: ''
- name: pipelineParameters
  default: ''
- name: agentPool
  default: 'default'
- name: notificationsGroup
  default: ''                                       #[Microsoft]\Pipeline Developers 
                                                    #syntax discussions here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/13320, https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines

stages:
  - stage: ${{parameters.stage}} 
    pool: 
      vmImage: 'ubuntu-latest'
    displayName: ${{parameters.displayName}} 
    dependsOn: ${{parameters.dependsOn}} 
    jobs:
    - job: InstallFlyway
      steps:
        - script: ls
        - script: 'sudo wget -qO- https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/10.12.0/flyway-commandline-10.12.0-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.12.0/flyway /usr/local/bin'
        - script: sudo export PATH="/usr/local/bin/flyway:$PATH"
        - script: echo $PATH


 
