parameters:
- name: stage
  default: stage
- name: displayName
  default: Deploy
- name: dependsOn
  default: ''
- name: pauseForCodeReview
  default: false
- name: failReleaseIfDriftDetected
  default: false
- name: staticCodeAnalysis
  default: false
- name: staticCodeAnalysisOnly
  default: false
- name: generateReport                              #This is the primary flag to turn off reports. TODO: Sanitize number of variables used here.
  default: true
- name: targetCredentials
  default: ''
- name: pipelineParameters
  default: ''
- name: agentPool
  default: 'default'
- name: notificationsGroup
  default: ''                                       #[Microsoft]\Pipeline Developers 
                                                    #syntax discussions here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/13320, https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines

stages:
  - stage: ${{parameters.stage}} 

    
    displayName: ${{parameters.displayName}} 
    dependsOn: ${{parameters.dependsOn}} 
    
    jobs:
        pool: 
      vmImage: 'ubuntu-latest'
    resources:
      containers:
      - container: flyway
        image: redgate/flyway
    - job: GetVersion
      displayName: Get Version
      steps:
      - checkout: templates
      - checkout: self
        name: source
      - script: flyway --version
    
    

 
